// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "common.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace message {

namespace {

const ::google::protobuf::Descriptor* int32array_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  int32array_reflection_ = NULL;
const ::google::protobuf::Descriptor* CrashmoMapBaseData_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CrashmoMapBaseData_reflection_ = NULL;
const ::google::protobuf::Descriptor* CrashMapData_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CrashMapData_reflection_ = NULL;
const ::google::protobuf::Descriptor* CrashPlayerInfo_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CrashPlayerInfo_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_common_2eproto() {
  protobuf_AddDesc_common_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "common.proto");
  GOOGLE_CHECK(file != NULL);
  int32array_descriptor_ = file->message_type(0);
  static const int int32array_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(int32array, data_),
  };
  int32array_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      int32array_descriptor_,
      int32array::default_instance_,
      int32array_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(int32array, _has_bits_[0]),
      -1,
      -1,
      sizeof(int32array),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(int32array, _internal_metadata_),
      -1);
  CrashmoMapBaseData_descriptor_ = file->message_type(1);
  static const int CrashmoMapBaseData_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CrashmoMapBaseData, width_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CrashmoMapBaseData, height_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CrashmoMapBaseData, map_data_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CrashmoMapBaseData, map_index_),
  };
  CrashmoMapBaseData_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      CrashmoMapBaseData_descriptor_,
      CrashmoMapBaseData::default_instance_,
      CrashmoMapBaseData_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CrashmoMapBaseData, _has_bits_[0]),
      -1,
      -1,
      sizeof(CrashmoMapBaseData),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CrashmoMapBaseData, _internal_metadata_),
      -1);
  CrashMapData_descriptor_ = file->message_type(2);
  static const int CrashMapData_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CrashMapData, data_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CrashMapData, mapname_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CrashMapData, creatername_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CrashMapData, section_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CrashMapData, number_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CrashMapData, create_time_),
  };
  CrashMapData_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      CrashMapData_descriptor_,
      CrashMapData::default_instance_,
      CrashMapData_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CrashMapData, _has_bits_[0]),
      -1,
      -1,
      sizeof(CrashMapData),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CrashMapData, _internal_metadata_),
      -1);
  CrashPlayerInfo_descriptor_ = file->message_type(3);
  static const int CrashPlayerInfo_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CrashPlayerInfo, account_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CrashPlayerInfo, pass_point_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CrashPlayerInfo, pass_section_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CrashPlayerInfo, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CrashPlayerInfo, incompletemap_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CrashPlayerInfo, completemap_),
  };
  CrashPlayerInfo_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      CrashPlayerInfo_descriptor_,
      CrashPlayerInfo::default_instance_,
      CrashPlayerInfo_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CrashPlayerInfo, _has_bits_[0]),
      -1,
      -1,
      sizeof(CrashPlayerInfo),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CrashPlayerInfo, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_common_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      int32array_descriptor_, &int32array::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      CrashmoMapBaseData_descriptor_, &CrashmoMapBaseData::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      CrashMapData_descriptor_, &CrashMapData::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      CrashPlayerInfo_descriptor_, &CrashPlayerInfo::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_common_2eproto() {
  delete int32array::default_instance_;
  delete int32array_reflection_;
  delete CrashmoMapBaseData::default_instance_;
  delete CrashmoMapBaseData_reflection_;
  delete CrashMapData::default_instance_;
  delete CrashMapData_reflection_;
  delete CrashPlayerInfo::default_instance_;
  delete CrashPlayerInfo_reflection_;
}

void protobuf_AddDesc_common_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\014common.proto\022\007message\"\032\n\nint32array\022\014\n"
    "\004data\030\001 \003(\005\"m\n\022CrashmoMapBaseData\022\r\n\005wid"
    "th\030\001 \002(\005\022\016\n\006height\030\002 \002(\005\022%\n\010map_data\030\003 \003"
    "(\0132\023.message.int32array\022\021\n\tmap_index\030\005 \002"
    "(\004\"\225\001\n\014CrashMapData\022)\n\004Data\030\001 \002(\0132\033.mess"
    "age.CrashmoMapBaseData\022\017\n\007MapName\030\002 \002(\t\022"
    "\023\n\013CreaterName\030\003 \002(\t\022\017\n\007Section\030\004 \002(\005\022\016\n"
    "\006number\030\005 \002(\005\022\023\n\013create_time\030\006 \002(\004\"\264\001\n\017C"
    "rashPlayerInfo\022\017\n\007account\030\001 \002(\004\022\022\n\npass_"
    "point\030\002 \002(\005\022\024\n\014pass_section\030\004 \002(\005\022\014\n\004nam"
    "e\030\005 \002(\t\022,\n\rIncompleteMap\030\006 \003(\0132\025.message"
    ".CrashMapData\022*\n\013CompleteMap\030\007 \003(\0132\025.mes"
    "sage.CrashMapData", 497);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "common.proto", &protobuf_RegisterTypes);
  int32array::default_instance_ = new int32array();
  CrashmoMapBaseData::default_instance_ = new CrashmoMapBaseData();
  CrashMapData::default_instance_ = new CrashMapData();
  CrashPlayerInfo::default_instance_ = new CrashPlayerInfo();
  int32array::default_instance_->InitAsDefaultInstance();
  CrashmoMapBaseData::default_instance_->InitAsDefaultInstance();
  CrashMapData::default_instance_->InitAsDefaultInstance();
  CrashPlayerInfo::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_common_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_common_2eproto {
  StaticDescriptorInitializer_common_2eproto() {
    protobuf_AddDesc_common_2eproto();
  }
} static_descriptor_initializer_common_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#ifndef _MSC_VER
const int int32array::kDataFieldNumber;
#endif  // !_MSC_VER

int32array::int32array()
  : ::google::protobuf::Message() , _internal_metadata_(NULL)  {
  SharedCtor();
  // @@protoc_insertion_point(constructor:message.int32array)
}

void int32array::InitAsDefaultInstance() {
}

int32array::int32array(const int32array& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:message.int32array)
}

void int32array::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

int32array::~int32array() {
  // @@protoc_insertion_point(destructor:message.int32array)
  SharedDtor();
}

void int32array::SharedDtor() {
  if (this != default_instance_) {
  }
}

void int32array::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* int32array::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return int32array_descriptor_;
}

const int32array& int32array::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_common_2eproto();
  return *default_instance_;
}

int32array* int32array::default_instance_ = NULL;

int32array* int32array::New(::google::protobuf::Arena* arena) const {
  int32array* n = new int32array;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void int32array::Clear() {
  data_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool int32array::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:message.int32array)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated int32 data = 1;
      case 1: {
        if (tag == 8) {
         parse_data:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 8, input, this->mutable_data())));
        } else if (tag == 10) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_data())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(8)) goto parse_data;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:message.int32array)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:message.int32array)
  return false;
#undef DO_
}

void int32array::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:message.int32array)
  // repeated int32 data = 1;
  for (int i = 0; i < this->data_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      1, this->data(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:message.int32array)
}

::google::protobuf::uint8* int32array::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:message.int32array)
  // repeated int32 data = 1;
  for (int i = 0; i < this->data_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(1, this->data(i), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:message.int32array)
  return target;
}

int int32array::ByteSize() const {
  int total_size = 0;

  // repeated int32 data = 1;
  {
    int data_size = 0;
    for (int i = 0; i < this->data_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->data(i));
    }
    total_size += 1 * this->data_size() + data_size;
  }

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void int32array::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const int32array* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const int32array*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void int32array::MergeFrom(const int32array& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  data_.MergeFrom(from.data_);
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void int32array::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void int32array::CopyFrom(const int32array& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool int32array::IsInitialized() const {

  return true;
}

void int32array::Swap(int32array* other) {
  if (other == this) return;
  InternalSwap(other);
}
void int32array::InternalSwap(int32array* other) {
  data_.UnsafeArenaSwap(&other->data_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata int32array::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = int32array_descriptor_;
  metadata.reflection = int32array_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// int32array

// repeated int32 data = 1;
 int int32array::data_size() const {
  return data_.size();
}
 void int32array::clear_data() {
  data_.Clear();
}
 ::google::protobuf::int32 int32array::data(int index) const {
  // @@protoc_insertion_point(field_get:message.int32array.data)
  return data_.Get(index);
}
 void int32array::set_data(int index, ::google::protobuf::int32 value) {
  data_.Set(index, value);
  // @@protoc_insertion_point(field_set:message.int32array.data)
}
 void int32array::add_data(::google::protobuf::int32 value) {
  data_.Add(value);
  // @@protoc_insertion_point(field_add:message.int32array.data)
}
 const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
int32array::data() const {
  // @@protoc_insertion_point(field_list:message.int32array.data)
  return data_;
}
 ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
int32array::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:message.int32array.data)
  return &data_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#ifndef _MSC_VER
const int CrashmoMapBaseData::kWidthFieldNumber;
const int CrashmoMapBaseData::kHeightFieldNumber;
const int CrashmoMapBaseData::kMapDataFieldNumber;
const int CrashmoMapBaseData::kMapIndexFieldNumber;
#endif  // !_MSC_VER

CrashmoMapBaseData::CrashmoMapBaseData()
  : ::google::protobuf::Message() , _internal_metadata_(NULL)  {
  SharedCtor();
  // @@protoc_insertion_point(constructor:message.CrashmoMapBaseData)
}

void CrashmoMapBaseData::InitAsDefaultInstance() {
}

CrashmoMapBaseData::CrashmoMapBaseData(const CrashmoMapBaseData& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:message.CrashmoMapBaseData)
}

void CrashmoMapBaseData::SharedCtor() {
  _cached_size_ = 0;
  width_ = 0;
  height_ = 0;
  map_index_ = GOOGLE_ULONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CrashmoMapBaseData::~CrashmoMapBaseData() {
  // @@protoc_insertion_point(destructor:message.CrashmoMapBaseData)
  SharedDtor();
}

void CrashmoMapBaseData::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CrashmoMapBaseData::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CrashmoMapBaseData::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CrashmoMapBaseData_descriptor_;
}

const CrashmoMapBaseData& CrashmoMapBaseData::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_common_2eproto();
  return *default_instance_;
}

CrashmoMapBaseData* CrashmoMapBaseData::default_instance_ = NULL;

CrashmoMapBaseData* CrashmoMapBaseData::New(::google::protobuf::Arena* arena) const {
  CrashmoMapBaseData* n = new CrashmoMapBaseData;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CrashmoMapBaseData::Clear() {
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<CrashmoMapBaseData*>(16)->f)

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  if (_has_bits_[0 / 32] & 11) {
    ZR_(width_, height_);
    map_index_ = GOOGLE_ULONGLONG(0);
  }

#undef ZR_HELPER_
#undef ZR_

  map_data_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool CrashmoMapBaseData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:message.CrashmoMapBaseData)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 width = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &width_)));
          set_has_width();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_height;
        break;
      }

      // required int32 height = 2;
      case 2: {
        if (tag == 16) {
         parse_height:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &height_)));
          set_has_height();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_map_data;
        break;
      }

      // repeated .message.int32array map_data = 3;
      case 3: {
        if (tag == 26) {
         parse_map_data:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_map_data()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_map_data;
        if (input->ExpectTag(40)) goto parse_map_index;
        break;
      }

      // required uint64 map_index = 5;
      case 5: {
        if (tag == 40) {
         parse_map_index:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &map_index_)));
          set_has_map_index();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:message.CrashmoMapBaseData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:message.CrashmoMapBaseData)
  return false;
#undef DO_
}

void CrashmoMapBaseData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:message.CrashmoMapBaseData)
  // required int32 width = 1;
  if (has_width()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->width(), output);
  }

  // required int32 height = 2;
  if (has_height()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->height(), output);
  }

  // repeated .message.int32array map_data = 3;
  for (unsigned int i = 0, n = this->map_data_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->map_data(i), output);
  }

  // required uint64 map_index = 5;
  if (has_map_index()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(5, this->map_index(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:message.CrashmoMapBaseData)
}

::google::protobuf::uint8* CrashmoMapBaseData::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:message.CrashmoMapBaseData)
  // required int32 width = 1;
  if (has_width()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->width(), target);
  }

  // required int32 height = 2;
  if (has_height()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->height(), target);
  }

  // repeated .message.int32array map_data = 3;
  for (unsigned int i = 0, n = this->map_data_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->map_data(i), target);
  }

  // required uint64 map_index = 5;
  if (has_map_index()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(5, this->map_index(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:message.CrashmoMapBaseData)
  return target;
}

int CrashmoMapBaseData::RequiredFieldsByteSizeFallback() const {
  int total_size = 0;

  if (has_width()) {
    // required int32 width = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->width());
  }

  if (has_height()) {
    // required int32 height = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->height());
  }

  if (has_map_index()) {
    // required uint64 map_index = 5;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->map_index());
  }

  return total_size;
}
int CrashmoMapBaseData::ByteSize() const {
  int total_size = 0;

  if (((_has_bits_[0] & 0x0000000b) ^ 0x0000000b) == 0) {  // All required fields are present.
    // required int32 width = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->width());

    // required int32 height = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->height());

    // required uint64 map_index = 5;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->map_index());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  // repeated .message.int32array map_data = 3;
  total_size += 1 * this->map_data_size();
  for (int i = 0; i < this->map_data_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->map_data(i));
  }

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CrashmoMapBaseData::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const CrashmoMapBaseData* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CrashmoMapBaseData*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CrashmoMapBaseData::MergeFrom(const CrashmoMapBaseData& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  map_data_.MergeFrom(from.map_data_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_width()) {
      set_width(from.width());
    }
    if (from.has_height()) {
      set_height(from.height());
    }
    if (from.has_map_index()) {
      set_map_index(from.map_index());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void CrashmoMapBaseData::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CrashmoMapBaseData::CopyFrom(const CrashmoMapBaseData& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CrashmoMapBaseData::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000b) != 0x0000000b) return false;

  return true;
}

void CrashmoMapBaseData::Swap(CrashmoMapBaseData* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CrashmoMapBaseData::InternalSwap(CrashmoMapBaseData* other) {
  std::swap(width_, other->width_);
  std::swap(height_, other->height_);
  map_data_.UnsafeArenaSwap(&other->map_data_);
  std::swap(map_index_, other->map_index_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CrashmoMapBaseData::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CrashmoMapBaseData_descriptor_;
  metadata.reflection = CrashmoMapBaseData_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CrashmoMapBaseData

// required int32 width = 1;
 bool CrashmoMapBaseData::has_width() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
 void CrashmoMapBaseData::set_has_width() {
  _has_bits_[0] |= 0x00000001u;
}
 void CrashmoMapBaseData::clear_has_width() {
  _has_bits_[0] &= ~0x00000001u;
}
 void CrashmoMapBaseData::clear_width() {
  width_ = 0;
  clear_has_width();
}
 ::google::protobuf::int32 CrashmoMapBaseData::width() const {
  // @@protoc_insertion_point(field_get:message.CrashmoMapBaseData.width)
  return width_;
}
 void CrashmoMapBaseData::set_width(::google::protobuf::int32 value) {
  set_has_width();
  width_ = value;
  // @@protoc_insertion_point(field_set:message.CrashmoMapBaseData.width)
}

// required int32 height = 2;
 bool CrashmoMapBaseData::has_height() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
 void CrashmoMapBaseData::set_has_height() {
  _has_bits_[0] |= 0x00000002u;
}
 void CrashmoMapBaseData::clear_has_height() {
  _has_bits_[0] &= ~0x00000002u;
}
 void CrashmoMapBaseData::clear_height() {
  height_ = 0;
  clear_has_height();
}
 ::google::protobuf::int32 CrashmoMapBaseData::height() const {
  // @@protoc_insertion_point(field_get:message.CrashmoMapBaseData.height)
  return height_;
}
 void CrashmoMapBaseData::set_height(::google::protobuf::int32 value) {
  set_has_height();
  height_ = value;
  // @@protoc_insertion_point(field_set:message.CrashmoMapBaseData.height)
}

// repeated .message.int32array map_data = 3;
 int CrashmoMapBaseData::map_data_size() const {
  return map_data_.size();
}
 void CrashmoMapBaseData::clear_map_data() {
  map_data_.Clear();
}
 const ::message::int32array& CrashmoMapBaseData::map_data(int index) const {
  // @@protoc_insertion_point(field_get:message.CrashmoMapBaseData.map_data)
  return map_data_.Get(index);
}
 ::message::int32array* CrashmoMapBaseData::mutable_map_data(int index) {
  // @@protoc_insertion_point(field_mutable:message.CrashmoMapBaseData.map_data)
  return map_data_.Mutable(index);
}
 ::message::int32array* CrashmoMapBaseData::add_map_data() {
  // @@protoc_insertion_point(field_add:message.CrashmoMapBaseData.map_data)
  return map_data_.Add();
}
 const ::google::protobuf::RepeatedPtrField< ::message::int32array >&
CrashmoMapBaseData::map_data() const {
  // @@protoc_insertion_point(field_list:message.CrashmoMapBaseData.map_data)
  return map_data_;
}
 ::google::protobuf::RepeatedPtrField< ::message::int32array >*
CrashmoMapBaseData::mutable_map_data() {
  // @@protoc_insertion_point(field_mutable_list:message.CrashmoMapBaseData.map_data)
  return &map_data_;
}

// required uint64 map_index = 5;
 bool CrashmoMapBaseData::has_map_index() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
 void CrashmoMapBaseData::set_has_map_index() {
  _has_bits_[0] |= 0x00000008u;
}
 void CrashmoMapBaseData::clear_has_map_index() {
  _has_bits_[0] &= ~0x00000008u;
}
 void CrashmoMapBaseData::clear_map_index() {
  map_index_ = GOOGLE_ULONGLONG(0);
  clear_has_map_index();
}
 ::google::protobuf::uint64 CrashmoMapBaseData::map_index() const {
  // @@protoc_insertion_point(field_get:message.CrashmoMapBaseData.map_index)
  return map_index_;
}
 void CrashmoMapBaseData::set_map_index(::google::protobuf::uint64 value) {
  set_has_map_index();
  map_index_ = value;
  // @@protoc_insertion_point(field_set:message.CrashmoMapBaseData.map_index)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#ifndef _MSC_VER
const int CrashMapData::kDataFieldNumber;
const int CrashMapData::kMapNameFieldNumber;
const int CrashMapData::kCreaterNameFieldNumber;
const int CrashMapData::kSectionFieldNumber;
const int CrashMapData::kNumberFieldNumber;
const int CrashMapData::kCreateTimeFieldNumber;
#endif  // !_MSC_VER

CrashMapData::CrashMapData()
  : ::google::protobuf::Message() , _internal_metadata_(NULL)  {
  SharedCtor();
  // @@protoc_insertion_point(constructor:message.CrashMapData)
}

void CrashMapData::InitAsDefaultInstance() {
  data_ = const_cast< ::message::CrashmoMapBaseData*>(&::message::CrashmoMapBaseData::default_instance());
}

CrashMapData::CrashMapData(const CrashMapData& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:message.CrashMapData)
}

void CrashMapData::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  data_ = NULL;
  mapname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  creatername_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  section_ = 0;
  number_ = 0;
  create_time_ = GOOGLE_ULONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CrashMapData::~CrashMapData() {
  // @@protoc_insertion_point(destructor:message.CrashMapData)
  SharedDtor();
}

void CrashMapData::SharedDtor() {
  mapname_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  creatername_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
    delete data_;
  }
}

void CrashMapData::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CrashMapData::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CrashMapData_descriptor_;
}

const CrashMapData& CrashMapData::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_common_2eproto();
  return *default_instance_;
}

CrashMapData* CrashMapData::default_instance_ = NULL;

CrashMapData* CrashMapData::New(::google::protobuf::Arena* arena) const {
  CrashMapData* n = new CrashMapData;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CrashMapData::Clear() {
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<CrashMapData*>(16)->f)

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  if (_has_bits_[0 / 32] & 63) {
    ZR_(section_, create_time_);
    if (has_data()) {
      if (data_ != NULL) data_->::message::CrashmoMapBaseData::Clear();
    }
    if (has_mapname()) {
      mapname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_creatername()) {
      creatername_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
  }

#undef ZR_HELPER_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool CrashMapData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:message.CrashMapData)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .message.CrashmoMapBaseData Data = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_data()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_MapName;
        break;
      }

      // required string MapName = 2;
      case 2: {
        if (tag == 18) {
         parse_MapName:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_mapname()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->mapname().data(), this->mapname().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "message.CrashMapData.MapName");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_CreaterName;
        break;
      }

      // required string CreaterName = 3;
      case 3: {
        if (tag == 26) {
         parse_CreaterName:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_creatername()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->creatername().data(), this->creatername().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "message.CrashMapData.CreaterName");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_Section;
        break;
      }

      // required int32 Section = 4;
      case 4: {
        if (tag == 32) {
         parse_Section:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &section_)));
          set_has_section();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_number;
        break;
      }

      // required int32 number = 5;
      case 5: {
        if (tag == 40) {
         parse_number:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &number_)));
          set_has_number();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(48)) goto parse_create_time;
        break;
      }

      // required uint64 create_time = 6;
      case 6: {
        if (tag == 48) {
         parse_create_time:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &create_time_)));
          set_has_create_time();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:message.CrashMapData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:message.CrashMapData)
  return false;
#undef DO_
}

void CrashMapData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:message.CrashMapData)
  // required .message.CrashmoMapBaseData Data = 1;
  if (has_data()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->data_, output);
  }

  // required string MapName = 2;
  if (has_mapname()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->mapname().data(), this->mapname().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "message.CrashMapData.MapName");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->mapname(), output);
  }

  // required string CreaterName = 3;
  if (has_creatername()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->creatername().data(), this->creatername().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "message.CrashMapData.CreaterName");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->creatername(), output);
  }

  // required int32 Section = 4;
  if (has_section()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->section(), output);
  }

  // required int32 number = 5;
  if (has_number()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->number(), output);
  }

  // required uint64 create_time = 6;
  if (has_create_time()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(6, this->create_time(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:message.CrashMapData)
}

::google::protobuf::uint8* CrashMapData::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:message.CrashMapData)
  // required .message.CrashmoMapBaseData Data = 1;
  if (has_data()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, *this->data_, target);
  }

  // required string MapName = 2;
  if (has_mapname()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->mapname().data(), this->mapname().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "message.CrashMapData.MapName");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->mapname(), target);
  }

  // required string CreaterName = 3;
  if (has_creatername()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->creatername().data(), this->creatername().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "message.CrashMapData.CreaterName");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->creatername(), target);
  }

  // required int32 Section = 4;
  if (has_section()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->section(), target);
  }

  // required int32 number = 5;
  if (has_number()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->number(), target);
  }

  // required uint64 create_time = 6;
  if (has_create_time()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(6, this->create_time(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:message.CrashMapData)
  return target;
}

int CrashMapData::RequiredFieldsByteSizeFallback() const {
  int total_size = 0;

  if (has_data()) {
    // required .message.CrashmoMapBaseData Data = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->data_);
  }

  if (has_mapname()) {
    // required string MapName = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->mapname());
  }

  if (has_creatername()) {
    // required string CreaterName = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->creatername());
  }

  if (has_section()) {
    // required int32 Section = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->section());
  }

  if (has_number()) {
    // required int32 number = 5;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->number());
  }

  if (has_create_time()) {
    // required uint64 create_time = 6;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->create_time());
  }

  return total_size;
}
int CrashMapData::ByteSize() const {
  int total_size = 0;

  if (((_has_bits_[0] & 0x0000003f) ^ 0x0000003f) == 0) {  // All required fields are present.
    // required .message.CrashmoMapBaseData Data = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->data_);

    // required string MapName = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->mapname());

    // required string CreaterName = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->creatername());

    // required int32 Section = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->section());

    // required int32 number = 5;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->number());

    // required uint64 create_time = 6;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->create_time());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CrashMapData::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const CrashMapData* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CrashMapData*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CrashMapData::MergeFrom(const CrashMapData& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_data()) {
      mutable_data()->::message::CrashmoMapBaseData::MergeFrom(from.data());
    }
    if (from.has_mapname()) {
      set_has_mapname();
      mapname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.mapname_);
    }
    if (from.has_creatername()) {
      set_has_creatername();
      creatername_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.creatername_);
    }
    if (from.has_section()) {
      set_section(from.section());
    }
    if (from.has_number()) {
      set_number(from.number());
    }
    if (from.has_create_time()) {
      set_create_time(from.create_time());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void CrashMapData::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CrashMapData::CopyFrom(const CrashMapData& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CrashMapData::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000003f) != 0x0000003f) return false;

  if (has_data()) {
    if (!this->data_->IsInitialized()) return false;
  }
  return true;
}

void CrashMapData::Swap(CrashMapData* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CrashMapData::InternalSwap(CrashMapData* other) {
  std::swap(data_, other->data_);
  mapname_.Swap(&other->mapname_);
  creatername_.Swap(&other->creatername_);
  std::swap(section_, other->section_);
  std::swap(number_, other->number_);
  std::swap(create_time_, other->create_time_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CrashMapData::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CrashMapData_descriptor_;
  metadata.reflection = CrashMapData_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CrashMapData

// required .message.CrashmoMapBaseData Data = 1;
 bool CrashMapData::has_data() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
 void CrashMapData::set_has_data() {
  _has_bits_[0] |= 0x00000001u;
}
 void CrashMapData::clear_has_data() {
  _has_bits_[0] &= ~0x00000001u;
}
 void CrashMapData::clear_data() {
  if (data_ != NULL) data_->::message::CrashmoMapBaseData::Clear();
  clear_has_data();
}
 const ::message::CrashmoMapBaseData& CrashMapData::data() const {
  // @@protoc_insertion_point(field_get:message.CrashMapData.Data)
  return data_ != NULL ? *data_ : *default_instance_->data_;
}
 ::message::CrashmoMapBaseData* CrashMapData::mutable_data() {
  set_has_data();
  if (data_ == NULL) {
    data_ = new ::message::CrashmoMapBaseData;
  }
  // @@protoc_insertion_point(field_mutable:message.CrashMapData.Data)
  return data_;
}
 ::message::CrashmoMapBaseData* CrashMapData::release_data() {
  clear_has_data();
  ::message::CrashmoMapBaseData* temp = data_;
  data_ = NULL;
  return temp;
}
 void CrashMapData::set_allocated_data(::message::CrashmoMapBaseData* data) {
  delete data_;
  data_ = data;
  if (data) {
    set_has_data();
  } else {
    clear_has_data();
  }
  // @@protoc_insertion_point(field_set_allocated:message.CrashMapData.Data)
}

// required string MapName = 2;
 bool CrashMapData::has_mapname() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
 void CrashMapData::set_has_mapname() {
  _has_bits_[0] |= 0x00000002u;
}
 void CrashMapData::clear_has_mapname() {
  _has_bits_[0] &= ~0x00000002u;
}
 void CrashMapData::clear_mapname() {
  mapname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_mapname();
}
 const ::std::string& CrashMapData::mapname() const {
  // @@protoc_insertion_point(field_get:message.CrashMapData.MapName)
  return mapname_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CrashMapData::set_mapname(const ::std::string& value) {
  set_has_mapname();
  mapname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:message.CrashMapData.MapName)
}
 void CrashMapData::set_mapname(const char* value) {
  set_has_mapname();
  mapname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:message.CrashMapData.MapName)
}
 void CrashMapData::set_mapname(const char* value, size_t size) {
  set_has_mapname();
  mapname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:message.CrashMapData.MapName)
}
 ::std::string* CrashMapData::mutable_mapname() {
  set_has_mapname();
  // @@protoc_insertion_point(field_mutable:message.CrashMapData.MapName)
  return mapname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* CrashMapData::release_mapname() {
  clear_has_mapname();
  return mapname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CrashMapData::set_allocated_mapname(::std::string* mapname) {
  if (mapname != NULL) {
    set_has_mapname();
  } else {
    clear_has_mapname();
  }
  mapname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), mapname);
  // @@protoc_insertion_point(field_set_allocated:message.CrashMapData.MapName)
}

// required string CreaterName = 3;
 bool CrashMapData::has_creatername() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
 void CrashMapData::set_has_creatername() {
  _has_bits_[0] |= 0x00000004u;
}
 void CrashMapData::clear_has_creatername() {
  _has_bits_[0] &= ~0x00000004u;
}
 void CrashMapData::clear_creatername() {
  creatername_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_creatername();
}
 const ::std::string& CrashMapData::creatername() const {
  // @@protoc_insertion_point(field_get:message.CrashMapData.CreaterName)
  return creatername_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CrashMapData::set_creatername(const ::std::string& value) {
  set_has_creatername();
  creatername_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:message.CrashMapData.CreaterName)
}
 void CrashMapData::set_creatername(const char* value) {
  set_has_creatername();
  creatername_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:message.CrashMapData.CreaterName)
}
 void CrashMapData::set_creatername(const char* value, size_t size) {
  set_has_creatername();
  creatername_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:message.CrashMapData.CreaterName)
}
 ::std::string* CrashMapData::mutable_creatername() {
  set_has_creatername();
  // @@protoc_insertion_point(field_mutable:message.CrashMapData.CreaterName)
  return creatername_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* CrashMapData::release_creatername() {
  clear_has_creatername();
  return creatername_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CrashMapData::set_allocated_creatername(::std::string* creatername) {
  if (creatername != NULL) {
    set_has_creatername();
  } else {
    clear_has_creatername();
  }
  creatername_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), creatername);
  // @@protoc_insertion_point(field_set_allocated:message.CrashMapData.CreaterName)
}

// required int32 Section = 4;
 bool CrashMapData::has_section() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
 void CrashMapData::set_has_section() {
  _has_bits_[0] |= 0x00000008u;
}
 void CrashMapData::clear_has_section() {
  _has_bits_[0] &= ~0x00000008u;
}
 void CrashMapData::clear_section() {
  section_ = 0;
  clear_has_section();
}
 ::google::protobuf::int32 CrashMapData::section() const {
  // @@protoc_insertion_point(field_get:message.CrashMapData.Section)
  return section_;
}
 void CrashMapData::set_section(::google::protobuf::int32 value) {
  set_has_section();
  section_ = value;
  // @@protoc_insertion_point(field_set:message.CrashMapData.Section)
}

// required int32 number = 5;
 bool CrashMapData::has_number() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
 void CrashMapData::set_has_number() {
  _has_bits_[0] |= 0x00000010u;
}
 void CrashMapData::clear_has_number() {
  _has_bits_[0] &= ~0x00000010u;
}
 void CrashMapData::clear_number() {
  number_ = 0;
  clear_has_number();
}
 ::google::protobuf::int32 CrashMapData::number() const {
  // @@protoc_insertion_point(field_get:message.CrashMapData.number)
  return number_;
}
 void CrashMapData::set_number(::google::protobuf::int32 value) {
  set_has_number();
  number_ = value;
  // @@protoc_insertion_point(field_set:message.CrashMapData.number)
}

// required uint64 create_time = 6;
 bool CrashMapData::has_create_time() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
 void CrashMapData::set_has_create_time() {
  _has_bits_[0] |= 0x00000020u;
}
 void CrashMapData::clear_has_create_time() {
  _has_bits_[0] &= ~0x00000020u;
}
 void CrashMapData::clear_create_time() {
  create_time_ = GOOGLE_ULONGLONG(0);
  clear_has_create_time();
}
 ::google::protobuf::uint64 CrashMapData::create_time() const {
  // @@protoc_insertion_point(field_get:message.CrashMapData.create_time)
  return create_time_;
}
 void CrashMapData::set_create_time(::google::protobuf::uint64 value) {
  set_has_create_time();
  create_time_ = value;
  // @@protoc_insertion_point(field_set:message.CrashMapData.create_time)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#ifndef _MSC_VER
const int CrashPlayerInfo::kAccountFieldNumber;
const int CrashPlayerInfo::kPassPointFieldNumber;
const int CrashPlayerInfo::kPassSectionFieldNumber;
const int CrashPlayerInfo::kNameFieldNumber;
const int CrashPlayerInfo::kIncompleteMapFieldNumber;
const int CrashPlayerInfo::kCompleteMapFieldNumber;
#endif  // !_MSC_VER

CrashPlayerInfo::CrashPlayerInfo()
  : ::google::protobuf::Message() , _internal_metadata_(NULL)  {
  SharedCtor();
  // @@protoc_insertion_point(constructor:message.CrashPlayerInfo)
}

void CrashPlayerInfo::InitAsDefaultInstance() {
}

CrashPlayerInfo::CrashPlayerInfo(const CrashPlayerInfo& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:message.CrashPlayerInfo)
}

void CrashPlayerInfo::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  account_ = GOOGLE_ULONGLONG(0);
  pass_point_ = 0;
  pass_section_ = 0;
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CrashPlayerInfo::~CrashPlayerInfo() {
  // @@protoc_insertion_point(destructor:message.CrashPlayerInfo)
  SharedDtor();
}

void CrashPlayerInfo::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void CrashPlayerInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CrashPlayerInfo::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CrashPlayerInfo_descriptor_;
}

const CrashPlayerInfo& CrashPlayerInfo::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_common_2eproto();
  return *default_instance_;
}

CrashPlayerInfo* CrashPlayerInfo::default_instance_ = NULL;

CrashPlayerInfo* CrashPlayerInfo::New(::google::protobuf::Arena* arena) const {
  CrashPlayerInfo* n = new CrashPlayerInfo;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CrashPlayerInfo::Clear() {
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<CrashPlayerInfo*>(16)->f)

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  if (_has_bits_[0 / 32] & 15) {
    ZR_(account_, pass_section_);
    if (has_name()) {
      name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
  }

#undef ZR_HELPER_
#undef ZR_

  incompletemap_.Clear();
  completemap_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool CrashPlayerInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:message.CrashPlayerInfo)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint64 account = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &account_)));
          set_has_account();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_pass_point;
        break;
      }

      // required int32 pass_point = 2;
      case 2: {
        if (tag == 16) {
         parse_pass_point:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &pass_point_)));
          set_has_pass_point();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_pass_section;
        break;
      }

      // required int32 pass_section = 4;
      case 4: {
        if (tag == 32) {
         parse_pass_section:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &pass_section_)));
          set_has_pass_section();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_name;
        break;
      }

      // required string name = 5;
      case 5: {
        if (tag == 42) {
         parse_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "message.CrashPlayerInfo.name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(50)) goto parse_IncompleteMap;
        break;
      }

      // repeated .message.CrashMapData IncompleteMap = 6;
      case 6: {
        if (tag == 50) {
         parse_IncompleteMap:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_incompletemap()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(50)) goto parse_IncompleteMap;
        if (input->ExpectTag(58)) goto parse_CompleteMap;
        break;
      }

      // repeated .message.CrashMapData CompleteMap = 7;
      case 7: {
        if (tag == 58) {
         parse_CompleteMap:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_completemap()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(58)) goto parse_CompleteMap;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:message.CrashPlayerInfo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:message.CrashPlayerInfo)
  return false;
#undef DO_
}

void CrashPlayerInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:message.CrashPlayerInfo)
  // required uint64 account = 1;
  if (has_account()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->account(), output);
  }

  // required int32 pass_point = 2;
  if (has_pass_point()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->pass_point(), output);
  }

  // required int32 pass_section = 4;
  if (has_pass_section()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->pass_section(), output);
  }

  // required string name = 5;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "message.CrashPlayerInfo.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->name(), output);
  }

  // repeated .message.CrashMapData IncompleteMap = 6;
  for (unsigned int i = 0, n = this->incompletemap_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6, this->incompletemap(i), output);
  }

  // repeated .message.CrashMapData CompleteMap = 7;
  for (unsigned int i = 0, n = this->completemap_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      7, this->completemap(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:message.CrashPlayerInfo)
}

::google::protobuf::uint8* CrashPlayerInfo::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:message.CrashPlayerInfo)
  // required uint64 account = 1;
  if (has_account()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->account(), target);
  }

  // required int32 pass_point = 2;
  if (has_pass_point()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->pass_point(), target);
  }

  // required int32 pass_section = 4;
  if (has_pass_section()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->pass_section(), target);
  }

  // required string name = 5;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "message.CrashPlayerInfo.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->name(), target);
  }

  // repeated .message.CrashMapData IncompleteMap = 6;
  for (unsigned int i = 0, n = this->incompletemap_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        6, this->incompletemap(i), target);
  }

  // repeated .message.CrashMapData CompleteMap = 7;
  for (unsigned int i = 0, n = this->completemap_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        7, this->completemap(i), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:message.CrashPlayerInfo)
  return target;
}

int CrashPlayerInfo::RequiredFieldsByteSizeFallback() const {
  int total_size = 0;

  if (has_account()) {
    // required uint64 account = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->account());
  }

  if (has_pass_point()) {
    // required int32 pass_point = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->pass_point());
  }

  if (has_pass_section()) {
    // required int32 pass_section = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->pass_section());
  }

  if (has_name()) {
    // required string name = 5;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  return total_size;
}
int CrashPlayerInfo::ByteSize() const {
  int total_size = 0;

  if (((_has_bits_[0] & 0x0000000f) ^ 0x0000000f) == 0) {  // All required fields are present.
    // required uint64 account = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->account());

    // required int32 pass_point = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->pass_point());

    // required int32 pass_section = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->pass_section());

    // required string name = 5;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  // repeated .message.CrashMapData IncompleteMap = 6;
  total_size += 1 * this->incompletemap_size();
  for (int i = 0; i < this->incompletemap_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->incompletemap(i));
  }

  // repeated .message.CrashMapData CompleteMap = 7;
  total_size += 1 * this->completemap_size();
  for (int i = 0; i < this->completemap_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->completemap(i));
  }

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CrashPlayerInfo::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const CrashPlayerInfo* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CrashPlayerInfo*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CrashPlayerInfo::MergeFrom(const CrashPlayerInfo& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  incompletemap_.MergeFrom(from.incompletemap_);
  completemap_.MergeFrom(from.completemap_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_account()) {
      set_account(from.account());
    }
    if (from.has_pass_point()) {
      set_pass_point(from.pass_point());
    }
    if (from.has_pass_section()) {
      set_pass_section(from.pass_section());
    }
    if (from.has_name()) {
      set_has_name();
      name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void CrashPlayerInfo::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CrashPlayerInfo::CopyFrom(const CrashPlayerInfo& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CrashPlayerInfo::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000f) != 0x0000000f) return false;

  if (!::google::protobuf::internal::AllAreInitialized(this->incompletemap())) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->completemap())) return false;
  return true;
}

void CrashPlayerInfo::Swap(CrashPlayerInfo* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CrashPlayerInfo::InternalSwap(CrashPlayerInfo* other) {
  std::swap(account_, other->account_);
  std::swap(pass_point_, other->pass_point_);
  std::swap(pass_section_, other->pass_section_);
  name_.Swap(&other->name_);
  incompletemap_.UnsafeArenaSwap(&other->incompletemap_);
  completemap_.UnsafeArenaSwap(&other->completemap_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CrashPlayerInfo::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CrashPlayerInfo_descriptor_;
  metadata.reflection = CrashPlayerInfo_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CrashPlayerInfo

// required uint64 account = 1;
 bool CrashPlayerInfo::has_account() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
 void CrashPlayerInfo::set_has_account() {
  _has_bits_[0] |= 0x00000001u;
}
 void CrashPlayerInfo::clear_has_account() {
  _has_bits_[0] &= ~0x00000001u;
}
 void CrashPlayerInfo::clear_account() {
  account_ = GOOGLE_ULONGLONG(0);
  clear_has_account();
}
 ::google::protobuf::uint64 CrashPlayerInfo::account() const {
  // @@protoc_insertion_point(field_get:message.CrashPlayerInfo.account)
  return account_;
}
 void CrashPlayerInfo::set_account(::google::protobuf::uint64 value) {
  set_has_account();
  account_ = value;
  // @@protoc_insertion_point(field_set:message.CrashPlayerInfo.account)
}

// required int32 pass_point = 2;
 bool CrashPlayerInfo::has_pass_point() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
 void CrashPlayerInfo::set_has_pass_point() {
  _has_bits_[0] |= 0x00000002u;
}
 void CrashPlayerInfo::clear_has_pass_point() {
  _has_bits_[0] &= ~0x00000002u;
}
 void CrashPlayerInfo::clear_pass_point() {
  pass_point_ = 0;
  clear_has_pass_point();
}
 ::google::protobuf::int32 CrashPlayerInfo::pass_point() const {
  // @@protoc_insertion_point(field_get:message.CrashPlayerInfo.pass_point)
  return pass_point_;
}
 void CrashPlayerInfo::set_pass_point(::google::protobuf::int32 value) {
  set_has_pass_point();
  pass_point_ = value;
  // @@protoc_insertion_point(field_set:message.CrashPlayerInfo.pass_point)
}

// required int32 pass_section = 4;
 bool CrashPlayerInfo::has_pass_section() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
 void CrashPlayerInfo::set_has_pass_section() {
  _has_bits_[0] |= 0x00000004u;
}
 void CrashPlayerInfo::clear_has_pass_section() {
  _has_bits_[0] &= ~0x00000004u;
}
 void CrashPlayerInfo::clear_pass_section() {
  pass_section_ = 0;
  clear_has_pass_section();
}
 ::google::protobuf::int32 CrashPlayerInfo::pass_section() const {
  // @@protoc_insertion_point(field_get:message.CrashPlayerInfo.pass_section)
  return pass_section_;
}
 void CrashPlayerInfo::set_pass_section(::google::protobuf::int32 value) {
  set_has_pass_section();
  pass_section_ = value;
  // @@protoc_insertion_point(field_set:message.CrashPlayerInfo.pass_section)
}

// required string name = 5;
 bool CrashPlayerInfo::has_name() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
 void CrashPlayerInfo::set_has_name() {
  _has_bits_[0] |= 0x00000008u;
}
 void CrashPlayerInfo::clear_has_name() {
  _has_bits_[0] &= ~0x00000008u;
}
 void CrashPlayerInfo::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
 const ::std::string& CrashPlayerInfo::name() const {
  // @@protoc_insertion_point(field_get:message.CrashPlayerInfo.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CrashPlayerInfo::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:message.CrashPlayerInfo.name)
}
 void CrashPlayerInfo::set_name(const char* value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:message.CrashPlayerInfo.name)
}
 void CrashPlayerInfo::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:message.CrashPlayerInfo.name)
}
 ::std::string* CrashPlayerInfo::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:message.CrashPlayerInfo.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* CrashPlayerInfo::release_name() {
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CrashPlayerInfo::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:message.CrashPlayerInfo.name)
}

// repeated .message.CrashMapData IncompleteMap = 6;
 int CrashPlayerInfo::incompletemap_size() const {
  return incompletemap_.size();
}
 void CrashPlayerInfo::clear_incompletemap() {
  incompletemap_.Clear();
}
 const ::message::CrashMapData& CrashPlayerInfo::incompletemap(int index) const {
  // @@protoc_insertion_point(field_get:message.CrashPlayerInfo.IncompleteMap)
  return incompletemap_.Get(index);
}
 ::message::CrashMapData* CrashPlayerInfo::mutable_incompletemap(int index) {
  // @@protoc_insertion_point(field_mutable:message.CrashPlayerInfo.IncompleteMap)
  return incompletemap_.Mutable(index);
}
 ::message::CrashMapData* CrashPlayerInfo::add_incompletemap() {
  // @@protoc_insertion_point(field_add:message.CrashPlayerInfo.IncompleteMap)
  return incompletemap_.Add();
}
 const ::google::protobuf::RepeatedPtrField< ::message::CrashMapData >&
CrashPlayerInfo::incompletemap() const {
  // @@protoc_insertion_point(field_list:message.CrashPlayerInfo.IncompleteMap)
  return incompletemap_;
}
 ::google::protobuf::RepeatedPtrField< ::message::CrashMapData >*
CrashPlayerInfo::mutable_incompletemap() {
  // @@protoc_insertion_point(field_mutable_list:message.CrashPlayerInfo.IncompleteMap)
  return &incompletemap_;
}

// repeated .message.CrashMapData CompleteMap = 7;
 int CrashPlayerInfo::completemap_size() const {
  return completemap_.size();
}
 void CrashPlayerInfo::clear_completemap() {
  completemap_.Clear();
}
 const ::message::CrashMapData& CrashPlayerInfo::completemap(int index) const {
  // @@protoc_insertion_point(field_get:message.CrashPlayerInfo.CompleteMap)
  return completemap_.Get(index);
}
 ::message::CrashMapData* CrashPlayerInfo::mutable_completemap(int index) {
  // @@protoc_insertion_point(field_mutable:message.CrashPlayerInfo.CompleteMap)
  return completemap_.Mutable(index);
}
 ::message::CrashMapData* CrashPlayerInfo::add_completemap() {
  // @@protoc_insertion_point(field_add:message.CrashPlayerInfo.CompleteMap)
  return completemap_.Add();
}
 const ::google::protobuf::RepeatedPtrField< ::message::CrashMapData >&
CrashPlayerInfo::completemap() const {
  // @@protoc_insertion_point(field_list:message.CrashPlayerInfo.CompleteMap)
  return completemap_;
}
 ::google::protobuf::RepeatedPtrField< ::message::CrashMapData >*
CrashPlayerInfo::mutable_completemap() {
  // @@protoc_insertion_point(field_mutable_list:message.CrashPlayerInfo.CompleteMap)
  return &completemap_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace message

// @@protoc_insertion_point(global_scope)
