// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

#ifndef PROTOBUF_common_2eproto__INCLUDED
#define PROTOBUF_common_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace message {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_common_2eproto();
void protobuf_AssignDesc_common_2eproto();
void protobuf_ShutdownFile_common_2eproto();

class int32array;
class CrashmoMapBaseData;
class CrashMapData;
class intPair;
class CrashPlayerInfo;

// ===================================================================

class int32array : public ::google::protobuf::Message {
 public:
  int32array();
  virtual ~int32array();

  int32array(const int32array& from);

  inline int32array& operator=(const int32array& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const int32array& default_instance();

  void Swap(int32array* other);

  // implements Message ----------------------------------------------

  inline int32array* New() const { return New(NULL); }

  int32array* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const int32array& from);
  void MergeFrom(const int32array& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(int32array* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 data = 1;
  int data_size() const;
  void clear_data();
  static const int kDataFieldNumber = 1;
  ::google::protobuf::int32 data(int index) const;
  void set_data(int index, ::google::protobuf::int32 value);
  void add_data(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      data() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_data();

  // @@protoc_insertion_point(class_scope:message.int32array)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > data_;
  friend void  protobuf_AddDesc_common_2eproto();
  friend void protobuf_AssignDesc_common_2eproto();
  friend void protobuf_ShutdownFile_common_2eproto();

  void InitAsDefaultInstance();
  static int32array* default_instance_;
};
// -------------------------------------------------------------------

class CrashmoMapBaseData : public ::google::protobuf::Message {
 public:
  CrashmoMapBaseData();
  virtual ~CrashmoMapBaseData();

  CrashmoMapBaseData(const CrashmoMapBaseData& from);

  inline CrashmoMapBaseData& operator=(const CrashmoMapBaseData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CrashmoMapBaseData& default_instance();

  void Swap(CrashmoMapBaseData* other);

  // implements Message ----------------------------------------------

  inline CrashmoMapBaseData* New() const { return New(NULL); }

  CrashmoMapBaseData* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CrashmoMapBaseData& from);
  void MergeFrom(const CrashmoMapBaseData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CrashmoMapBaseData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 width = 1;
  bool has_width() const;
  void clear_width();
  static const int kWidthFieldNumber = 1;
  ::google::protobuf::int32 width() const;
  void set_width(::google::protobuf::int32 value);

  // required int32 height = 2;
  bool has_height() const;
  void clear_height();
  static const int kHeightFieldNumber = 2;
  ::google::protobuf::int32 height() const;
  void set_height(::google::protobuf::int32 value);

  // repeated .message.int32array map_data = 3;
  int map_data_size() const;
  void clear_map_data();
  static const int kMapDataFieldNumber = 3;
  const ::message::int32array& map_data(int index) const;
  ::message::int32array* mutable_map_data(int index);
  ::message::int32array* add_map_data();
  const ::google::protobuf::RepeatedPtrField< ::message::int32array >&
      map_data() const;
  ::google::protobuf::RepeatedPtrField< ::message::int32array >*
      mutable_map_data();

  // required uint64 map_index = 5;
  bool has_map_index() const;
  void clear_map_index();
  static const int kMapIndexFieldNumber = 5;
  ::google::protobuf::uint64 map_index() const;
  void set_map_index(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:message.CrashmoMapBaseData)
 private:
  inline void set_has_width();
  inline void clear_has_width();
  inline void set_has_height();
  inline void clear_has_height();
  inline void set_has_map_index();
  inline void clear_has_map_index();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 width_;
  ::google::protobuf::int32 height_;
  ::google::protobuf::RepeatedPtrField< ::message::int32array > map_data_;
  ::google::protobuf::uint64 map_index_;
  friend void  protobuf_AddDesc_common_2eproto();
  friend void protobuf_AssignDesc_common_2eproto();
  friend void protobuf_ShutdownFile_common_2eproto();

  void InitAsDefaultInstance();
  static CrashmoMapBaseData* default_instance_;
};
// -------------------------------------------------------------------

class CrashMapData : public ::google::protobuf::Message {
 public:
  CrashMapData();
  virtual ~CrashMapData();

  CrashMapData(const CrashMapData& from);

  inline CrashMapData& operator=(const CrashMapData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CrashMapData& default_instance();

  void Swap(CrashMapData* other);

  // implements Message ----------------------------------------------

  inline CrashMapData* New() const { return New(NULL); }

  CrashMapData* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CrashMapData& from);
  void MergeFrom(const CrashMapData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CrashMapData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .message.CrashmoMapBaseData Data = 1;
  bool has_data() const;
  void clear_data();
  static const int kDataFieldNumber = 1;
  const ::message::CrashmoMapBaseData& data() const;
  ::message::CrashmoMapBaseData* mutable_data();
  ::message::CrashmoMapBaseData* release_data();
  void set_allocated_data(::message::CrashmoMapBaseData* data);

  // required string MapName = 2;
  bool has_mapname() const;
  void clear_mapname();
  static const int kMapNameFieldNumber = 2;
  const ::std::string& mapname() const;
  void set_mapname(const ::std::string& value);
  void set_mapname(const char* value);
  void set_mapname(const char* value, size_t size);
  ::std::string* mutable_mapname();
  ::std::string* release_mapname();
  void set_allocated_mapname(::std::string* mapname);

  // required string CreaterName = 3;
  bool has_creatername() const;
  void clear_creatername();
  static const int kCreaterNameFieldNumber = 3;
  const ::std::string& creatername() const;
  void set_creatername(const ::std::string& value);
  void set_creatername(const char* value);
  void set_creatername(const char* value, size_t size);
  ::std::string* mutable_creatername();
  ::std::string* release_creatername();
  void set_allocated_creatername(::std::string* creatername);

  // required int32 Section = 4;
  bool has_section() const;
  void clear_section();
  static const int kSectionFieldNumber = 4;
  ::google::protobuf::int32 section() const;
  void set_section(::google::protobuf::int32 value);

  // required int32 number = 5;
  bool has_number() const;
  void clear_number();
  static const int kNumberFieldNumber = 5;
  ::google::protobuf::int32 number() const;
  void set_number(::google::protobuf::int32 value);

  // required uint64 create_time = 6;
  bool has_create_time() const;
  void clear_create_time();
  static const int kCreateTimeFieldNumber = 6;
  ::google::protobuf::uint64 create_time() const;
  void set_create_time(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:message.CrashMapData)
 private:
  inline void set_has_data();
  inline void clear_has_data();
  inline void set_has_mapname();
  inline void clear_has_mapname();
  inline void set_has_creatername();
  inline void clear_has_creatername();
  inline void set_has_section();
  inline void clear_has_section();
  inline void set_has_number();
  inline void clear_has_number();
  inline void set_has_create_time();
  inline void clear_has_create_time();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::message::CrashmoMapBaseData* data_;
  ::google::protobuf::internal::ArenaStringPtr mapname_;
  ::google::protobuf::internal::ArenaStringPtr creatername_;
  ::google::protobuf::int32 section_;
  ::google::protobuf::int32 number_;
  ::google::protobuf::uint64 create_time_;
  friend void  protobuf_AddDesc_common_2eproto();
  friend void protobuf_AssignDesc_common_2eproto();
  friend void protobuf_ShutdownFile_common_2eproto();

  void InitAsDefaultInstance();
  static CrashMapData* default_instance_;
};
// -------------------------------------------------------------------

class intPair : public ::google::protobuf::Message {
 public:
  intPair();
  virtual ~intPair();

  intPair(const intPair& from);

  inline intPair& operator=(const intPair& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const intPair& default_instance();

  void Swap(intPair* other);

  // implements Message ----------------------------------------------

  inline intPair* New() const { return New(NULL); }

  intPair* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const intPair& from);
  void MergeFrom(const intPair& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(intPair* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 number_1 = 1;
  bool has_number_1() const;
  void clear_number_1();
  static const int kNumber1FieldNumber = 1;
  ::google::protobuf::int32 number_1() const;
  void set_number_1(::google::protobuf::int32 value);

  // required int32 number_2 = 2;
  bool has_number_2() const;
  void clear_number_2();
  static const int kNumber2FieldNumber = 2;
  ::google::protobuf::int32 number_2() const;
  void set_number_2(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:message.intPair)
 private:
  inline void set_has_number_1();
  inline void clear_has_number_1();
  inline void set_has_number_2();
  inline void clear_has_number_2();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 number_1_;
  ::google::protobuf::int32 number_2_;
  friend void  protobuf_AddDesc_common_2eproto();
  friend void protobuf_AssignDesc_common_2eproto();
  friend void protobuf_ShutdownFile_common_2eproto();

  void InitAsDefaultInstance();
  static intPair* default_instance_;
};
// -------------------------------------------------------------------

class CrashPlayerInfo : public ::google::protobuf::Message {
 public:
  CrashPlayerInfo();
  virtual ~CrashPlayerInfo();

  CrashPlayerInfo(const CrashPlayerInfo& from);

  inline CrashPlayerInfo& operator=(const CrashPlayerInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CrashPlayerInfo& default_instance();

  void Swap(CrashPlayerInfo* other);

  // implements Message ----------------------------------------------

  inline CrashPlayerInfo* New() const { return New(NULL); }

  CrashPlayerInfo* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CrashPlayerInfo& from);
  void MergeFrom(const CrashPlayerInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CrashPlayerInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 account = 1;
  bool has_account() const;
  void clear_account();
  static const int kAccountFieldNumber = 1;
  ::google::protobuf::uint64 account() const;
  void set_account(::google::protobuf::uint64 value);

  // required int32 pass_point = 2;
  bool has_pass_point() const;
  void clear_pass_point();
  static const int kPassPointFieldNumber = 2;
  ::google::protobuf::int32 pass_point() const;
  void set_pass_point(::google::protobuf::int32 value);

  // required int32 pass_section = 4;
  bool has_pass_section() const;
  void clear_pass_section();
  static const int kPassSectionFieldNumber = 4;
  ::google::protobuf::int32 pass_section() const;
  void set_pass_section(::google::protobuf::int32 value);

  // required string name = 5;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 5;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // repeated .message.CrashMapData IncompleteMap = 6;
  int incompletemap_size() const;
  void clear_incompletemap();
  static const int kIncompleteMapFieldNumber = 6;
  const ::message::CrashMapData& incompletemap(int index) const;
  ::message::CrashMapData* mutable_incompletemap(int index);
  ::message::CrashMapData* add_incompletemap();
  const ::google::protobuf::RepeatedPtrField< ::message::CrashMapData >&
      incompletemap() const;
  ::google::protobuf::RepeatedPtrField< ::message::CrashMapData >*
      mutable_incompletemap();

  // repeated .message.CrashMapData CompleteMap = 7;
  int completemap_size() const;
  void clear_completemap();
  static const int kCompleteMapFieldNumber = 7;
  const ::message::CrashMapData& completemap(int index) const;
  ::message::CrashMapData* mutable_completemap(int index);
  ::message::CrashMapData* add_completemap();
  const ::google::protobuf::RepeatedPtrField< ::message::CrashMapData >&
      completemap() const;
  ::google::protobuf::RepeatedPtrField< ::message::CrashMapData >*
      mutable_completemap();

  // required bool isadmin = 8;
  bool has_isadmin() const;
  void clear_isadmin();
  static const int kIsadminFieldNumber = 8;
  bool isadmin() const;
  void set_isadmin(bool value);

  // repeated .message.intPair resources = 9;
  int resources_size() const;
  void clear_resources();
  static const int kResourcesFieldNumber = 9;
  const ::message::intPair& resources(int index) const;
  ::message::intPair* mutable_resources(int index);
  ::message::intPair* add_resources();
  const ::google::protobuf::RepeatedPtrField< ::message::intPair >&
      resources() const;
  ::google::protobuf::RepeatedPtrField< ::message::intPair >*
      mutable_resources();

  // @@protoc_insertion_point(class_scope:message.CrashPlayerInfo)
 private:
  inline void set_has_account();
  inline void clear_has_account();
  inline void set_has_pass_point();
  inline void clear_has_pass_point();
  inline void set_has_pass_section();
  inline void clear_has_pass_section();
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_isadmin();
  inline void clear_has_isadmin();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 account_;
  ::google::protobuf::int32 pass_point_;
  ::google::protobuf::int32 pass_section_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::RepeatedPtrField< ::message::CrashMapData > incompletemap_;
  ::google::protobuf::RepeatedPtrField< ::message::CrashMapData > completemap_;
  ::google::protobuf::RepeatedPtrField< ::message::intPair > resources_;
  bool isadmin_;
  friend void  protobuf_AddDesc_common_2eproto();
  friend void protobuf_AssignDesc_common_2eproto();
  friend void protobuf_ShutdownFile_common_2eproto();

  void InitAsDefaultInstance();
  static CrashPlayerInfo* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// int32array

// repeated int32 data = 1;
inline int int32array::data_size() const {
  return data_.size();
}
inline void int32array::clear_data() {
  data_.Clear();
}
inline ::google::protobuf::int32 int32array::data(int index) const {
  // @@protoc_insertion_point(field_get:message.int32array.data)
  return data_.Get(index);
}
inline void int32array::set_data(int index, ::google::protobuf::int32 value) {
  data_.Set(index, value);
  // @@protoc_insertion_point(field_set:message.int32array.data)
}
inline void int32array::add_data(::google::protobuf::int32 value) {
  data_.Add(value);
  // @@protoc_insertion_point(field_add:message.int32array.data)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
int32array::data() const {
  // @@protoc_insertion_point(field_list:message.int32array.data)
  return data_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
int32array::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:message.int32array.data)
  return &data_;
}

// -------------------------------------------------------------------

// CrashmoMapBaseData

// required int32 width = 1;
inline bool CrashmoMapBaseData::has_width() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CrashmoMapBaseData::set_has_width() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CrashmoMapBaseData::clear_has_width() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CrashmoMapBaseData::clear_width() {
  width_ = 0;
  clear_has_width();
}
inline ::google::protobuf::int32 CrashmoMapBaseData::width() const {
  // @@protoc_insertion_point(field_get:message.CrashmoMapBaseData.width)
  return width_;
}
inline void CrashmoMapBaseData::set_width(::google::protobuf::int32 value) {
  set_has_width();
  width_ = value;
  // @@protoc_insertion_point(field_set:message.CrashmoMapBaseData.width)
}

// required int32 height = 2;
inline bool CrashmoMapBaseData::has_height() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CrashmoMapBaseData::set_has_height() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CrashmoMapBaseData::clear_has_height() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CrashmoMapBaseData::clear_height() {
  height_ = 0;
  clear_has_height();
}
inline ::google::protobuf::int32 CrashmoMapBaseData::height() const {
  // @@protoc_insertion_point(field_get:message.CrashmoMapBaseData.height)
  return height_;
}
inline void CrashmoMapBaseData::set_height(::google::protobuf::int32 value) {
  set_has_height();
  height_ = value;
  // @@protoc_insertion_point(field_set:message.CrashmoMapBaseData.height)
}

// repeated .message.int32array map_data = 3;
inline int CrashmoMapBaseData::map_data_size() const {
  return map_data_.size();
}
inline void CrashmoMapBaseData::clear_map_data() {
  map_data_.Clear();
}
inline const ::message::int32array& CrashmoMapBaseData::map_data(int index) const {
  // @@protoc_insertion_point(field_get:message.CrashmoMapBaseData.map_data)
  return map_data_.Get(index);
}
inline ::message::int32array* CrashmoMapBaseData::mutable_map_data(int index) {
  // @@protoc_insertion_point(field_mutable:message.CrashmoMapBaseData.map_data)
  return map_data_.Mutable(index);
}
inline ::message::int32array* CrashmoMapBaseData::add_map_data() {
  // @@protoc_insertion_point(field_add:message.CrashmoMapBaseData.map_data)
  return map_data_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::message::int32array >&
CrashmoMapBaseData::map_data() const {
  // @@protoc_insertion_point(field_list:message.CrashmoMapBaseData.map_data)
  return map_data_;
}
inline ::google::protobuf::RepeatedPtrField< ::message::int32array >*
CrashmoMapBaseData::mutable_map_data() {
  // @@protoc_insertion_point(field_mutable_list:message.CrashmoMapBaseData.map_data)
  return &map_data_;
}

// required uint64 map_index = 5;
inline bool CrashmoMapBaseData::has_map_index() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void CrashmoMapBaseData::set_has_map_index() {
  _has_bits_[0] |= 0x00000008u;
}
inline void CrashmoMapBaseData::clear_has_map_index() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void CrashmoMapBaseData::clear_map_index() {
  map_index_ = GOOGLE_ULONGLONG(0);
  clear_has_map_index();
}
inline ::google::protobuf::uint64 CrashmoMapBaseData::map_index() const {
  // @@protoc_insertion_point(field_get:message.CrashmoMapBaseData.map_index)
  return map_index_;
}
inline void CrashmoMapBaseData::set_map_index(::google::protobuf::uint64 value) {
  set_has_map_index();
  map_index_ = value;
  // @@protoc_insertion_point(field_set:message.CrashmoMapBaseData.map_index)
}

// -------------------------------------------------------------------

// CrashMapData

// required .message.CrashmoMapBaseData Data = 1;
inline bool CrashMapData::has_data() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CrashMapData::set_has_data() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CrashMapData::clear_has_data() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CrashMapData::clear_data() {
  if (data_ != NULL) data_->::message::CrashmoMapBaseData::Clear();
  clear_has_data();
}
inline const ::message::CrashmoMapBaseData& CrashMapData::data() const {
  // @@protoc_insertion_point(field_get:message.CrashMapData.Data)
  return data_ != NULL ? *data_ : *default_instance_->data_;
}
inline ::message::CrashmoMapBaseData* CrashMapData::mutable_data() {
  set_has_data();
  if (data_ == NULL) {
    data_ = new ::message::CrashmoMapBaseData;
  }
  // @@protoc_insertion_point(field_mutable:message.CrashMapData.Data)
  return data_;
}
inline ::message::CrashmoMapBaseData* CrashMapData::release_data() {
  clear_has_data();
  ::message::CrashmoMapBaseData* temp = data_;
  data_ = NULL;
  return temp;
}
inline void CrashMapData::set_allocated_data(::message::CrashmoMapBaseData* data) {
  delete data_;
  data_ = data;
  if (data) {
    set_has_data();
  } else {
    clear_has_data();
  }
  // @@protoc_insertion_point(field_set_allocated:message.CrashMapData.Data)
}

// required string MapName = 2;
inline bool CrashMapData::has_mapname() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CrashMapData::set_has_mapname() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CrashMapData::clear_has_mapname() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CrashMapData::clear_mapname() {
  mapname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_mapname();
}
inline const ::std::string& CrashMapData::mapname() const {
  // @@protoc_insertion_point(field_get:message.CrashMapData.MapName)
  return mapname_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CrashMapData::set_mapname(const ::std::string& value) {
  set_has_mapname();
  mapname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:message.CrashMapData.MapName)
}
inline void CrashMapData::set_mapname(const char* value) {
  set_has_mapname();
  mapname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:message.CrashMapData.MapName)
}
inline void CrashMapData::set_mapname(const char* value, size_t size) {
  set_has_mapname();
  mapname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:message.CrashMapData.MapName)
}
inline ::std::string* CrashMapData::mutable_mapname() {
  set_has_mapname();
  // @@protoc_insertion_point(field_mutable:message.CrashMapData.MapName)
  return mapname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CrashMapData::release_mapname() {
  clear_has_mapname();
  return mapname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CrashMapData::set_allocated_mapname(::std::string* mapname) {
  if (mapname != NULL) {
    set_has_mapname();
  } else {
    clear_has_mapname();
  }
  mapname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), mapname);
  // @@protoc_insertion_point(field_set_allocated:message.CrashMapData.MapName)
}

// required string CreaterName = 3;
inline bool CrashMapData::has_creatername() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CrashMapData::set_has_creatername() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CrashMapData::clear_has_creatername() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CrashMapData::clear_creatername() {
  creatername_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_creatername();
}
inline const ::std::string& CrashMapData::creatername() const {
  // @@protoc_insertion_point(field_get:message.CrashMapData.CreaterName)
  return creatername_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CrashMapData::set_creatername(const ::std::string& value) {
  set_has_creatername();
  creatername_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:message.CrashMapData.CreaterName)
}
inline void CrashMapData::set_creatername(const char* value) {
  set_has_creatername();
  creatername_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:message.CrashMapData.CreaterName)
}
inline void CrashMapData::set_creatername(const char* value, size_t size) {
  set_has_creatername();
  creatername_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:message.CrashMapData.CreaterName)
}
inline ::std::string* CrashMapData::mutable_creatername() {
  set_has_creatername();
  // @@protoc_insertion_point(field_mutable:message.CrashMapData.CreaterName)
  return creatername_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CrashMapData::release_creatername() {
  clear_has_creatername();
  return creatername_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CrashMapData::set_allocated_creatername(::std::string* creatername) {
  if (creatername != NULL) {
    set_has_creatername();
  } else {
    clear_has_creatername();
  }
  creatername_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), creatername);
  // @@protoc_insertion_point(field_set_allocated:message.CrashMapData.CreaterName)
}

// required int32 Section = 4;
inline bool CrashMapData::has_section() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void CrashMapData::set_has_section() {
  _has_bits_[0] |= 0x00000008u;
}
inline void CrashMapData::clear_has_section() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void CrashMapData::clear_section() {
  section_ = 0;
  clear_has_section();
}
inline ::google::protobuf::int32 CrashMapData::section() const {
  // @@protoc_insertion_point(field_get:message.CrashMapData.Section)
  return section_;
}
inline void CrashMapData::set_section(::google::protobuf::int32 value) {
  set_has_section();
  section_ = value;
  // @@protoc_insertion_point(field_set:message.CrashMapData.Section)
}

// required int32 number = 5;
inline bool CrashMapData::has_number() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void CrashMapData::set_has_number() {
  _has_bits_[0] |= 0x00000010u;
}
inline void CrashMapData::clear_has_number() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void CrashMapData::clear_number() {
  number_ = 0;
  clear_has_number();
}
inline ::google::protobuf::int32 CrashMapData::number() const {
  // @@protoc_insertion_point(field_get:message.CrashMapData.number)
  return number_;
}
inline void CrashMapData::set_number(::google::protobuf::int32 value) {
  set_has_number();
  number_ = value;
  // @@protoc_insertion_point(field_set:message.CrashMapData.number)
}

// required uint64 create_time = 6;
inline bool CrashMapData::has_create_time() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void CrashMapData::set_has_create_time() {
  _has_bits_[0] |= 0x00000020u;
}
inline void CrashMapData::clear_has_create_time() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void CrashMapData::clear_create_time() {
  create_time_ = GOOGLE_ULONGLONG(0);
  clear_has_create_time();
}
inline ::google::protobuf::uint64 CrashMapData::create_time() const {
  // @@protoc_insertion_point(field_get:message.CrashMapData.create_time)
  return create_time_;
}
inline void CrashMapData::set_create_time(::google::protobuf::uint64 value) {
  set_has_create_time();
  create_time_ = value;
  // @@protoc_insertion_point(field_set:message.CrashMapData.create_time)
}

// -------------------------------------------------------------------

// intPair

// required int32 number_1 = 1;
inline bool intPair::has_number_1() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void intPair::set_has_number_1() {
  _has_bits_[0] |= 0x00000001u;
}
inline void intPair::clear_has_number_1() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void intPair::clear_number_1() {
  number_1_ = 0;
  clear_has_number_1();
}
inline ::google::protobuf::int32 intPair::number_1() const {
  // @@protoc_insertion_point(field_get:message.intPair.number_1)
  return number_1_;
}
inline void intPair::set_number_1(::google::protobuf::int32 value) {
  set_has_number_1();
  number_1_ = value;
  // @@protoc_insertion_point(field_set:message.intPair.number_1)
}

// required int32 number_2 = 2;
inline bool intPair::has_number_2() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void intPair::set_has_number_2() {
  _has_bits_[0] |= 0x00000002u;
}
inline void intPair::clear_has_number_2() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void intPair::clear_number_2() {
  number_2_ = 0;
  clear_has_number_2();
}
inline ::google::protobuf::int32 intPair::number_2() const {
  // @@protoc_insertion_point(field_get:message.intPair.number_2)
  return number_2_;
}
inline void intPair::set_number_2(::google::protobuf::int32 value) {
  set_has_number_2();
  number_2_ = value;
  // @@protoc_insertion_point(field_set:message.intPair.number_2)
}

// -------------------------------------------------------------------

// CrashPlayerInfo

// required uint64 account = 1;
inline bool CrashPlayerInfo::has_account() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CrashPlayerInfo::set_has_account() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CrashPlayerInfo::clear_has_account() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CrashPlayerInfo::clear_account() {
  account_ = GOOGLE_ULONGLONG(0);
  clear_has_account();
}
inline ::google::protobuf::uint64 CrashPlayerInfo::account() const {
  // @@protoc_insertion_point(field_get:message.CrashPlayerInfo.account)
  return account_;
}
inline void CrashPlayerInfo::set_account(::google::protobuf::uint64 value) {
  set_has_account();
  account_ = value;
  // @@protoc_insertion_point(field_set:message.CrashPlayerInfo.account)
}

// required int32 pass_point = 2;
inline bool CrashPlayerInfo::has_pass_point() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CrashPlayerInfo::set_has_pass_point() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CrashPlayerInfo::clear_has_pass_point() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CrashPlayerInfo::clear_pass_point() {
  pass_point_ = 0;
  clear_has_pass_point();
}
inline ::google::protobuf::int32 CrashPlayerInfo::pass_point() const {
  // @@protoc_insertion_point(field_get:message.CrashPlayerInfo.pass_point)
  return pass_point_;
}
inline void CrashPlayerInfo::set_pass_point(::google::protobuf::int32 value) {
  set_has_pass_point();
  pass_point_ = value;
  // @@protoc_insertion_point(field_set:message.CrashPlayerInfo.pass_point)
}

// required int32 pass_section = 4;
inline bool CrashPlayerInfo::has_pass_section() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CrashPlayerInfo::set_has_pass_section() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CrashPlayerInfo::clear_has_pass_section() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CrashPlayerInfo::clear_pass_section() {
  pass_section_ = 0;
  clear_has_pass_section();
}
inline ::google::protobuf::int32 CrashPlayerInfo::pass_section() const {
  // @@protoc_insertion_point(field_get:message.CrashPlayerInfo.pass_section)
  return pass_section_;
}
inline void CrashPlayerInfo::set_pass_section(::google::protobuf::int32 value) {
  set_has_pass_section();
  pass_section_ = value;
  // @@protoc_insertion_point(field_set:message.CrashPlayerInfo.pass_section)
}

// required string name = 5;
inline bool CrashPlayerInfo::has_name() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void CrashPlayerInfo::set_has_name() {
  _has_bits_[0] |= 0x00000008u;
}
inline void CrashPlayerInfo::clear_has_name() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void CrashPlayerInfo::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& CrashPlayerInfo::name() const {
  // @@protoc_insertion_point(field_get:message.CrashPlayerInfo.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CrashPlayerInfo::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:message.CrashPlayerInfo.name)
}
inline void CrashPlayerInfo::set_name(const char* value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:message.CrashPlayerInfo.name)
}
inline void CrashPlayerInfo::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:message.CrashPlayerInfo.name)
}
inline ::std::string* CrashPlayerInfo::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:message.CrashPlayerInfo.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CrashPlayerInfo::release_name() {
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CrashPlayerInfo::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:message.CrashPlayerInfo.name)
}

// repeated .message.CrashMapData IncompleteMap = 6;
inline int CrashPlayerInfo::incompletemap_size() const {
  return incompletemap_.size();
}
inline void CrashPlayerInfo::clear_incompletemap() {
  incompletemap_.Clear();
}
inline const ::message::CrashMapData& CrashPlayerInfo::incompletemap(int index) const {
  // @@protoc_insertion_point(field_get:message.CrashPlayerInfo.IncompleteMap)
  return incompletemap_.Get(index);
}
inline ::message::CrashMapData* CrashPlayerInfo::mutable_incompletemap(int index) {
  // @@protoc_insertion_point(field_mutable:message.CrashPlayerInfo.IncompleteMap)
  return incompletemap_.Mutable(index);
}
inline ::message::CrashMapData* CrashPlayerInfo::add_incompletemap() {
  // @@protoc_insertion_point(field_add:message.CrashPlayerInfo.IncompleteMap)
  return incompletemap_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::message::CrashMapData >&
CrashPlayerInfo::incompletemap() const {
  // @@protoc_insertion_point(field_list:message.CrashPlayerInfo.IncompleteMap)
  return incompletemap_;
}
inline ::google::protobuf::RepeatedPtrField< ::message::CrashMapData >*
CrashPlayerInfo::mutable_incompletemap() {
  // @@protoc_insertion_point(field_mutable_list:message.CrashPlayerInfo.IncompleteMap)
  return &incompletemap_;
}

// repeated .message.CrashMapData CompleteMap = 7;
inline int CrashPlayerInfo::completemap_size() const {
  return completemap_.size();
}
inline void CrashPlayerInfo::clear_completemap() {
  completemap_.Clear();
}
inline const ::message::CrashMapData& CrashPlayerInfo::completemap(int index) const {
  // @@protoc_insertion_point(field_get:message.CrashPlayerInfo.CompleteMap)
  return completemap_.Get(index);
}
inline ::message::CrashMapData* CrashPlayerInfo::mutable_completemap(int index) {
  // @@protoc_insertion_point(field_mutable:message.CrashPlayerInfo.CompleteMap)
  return completemap_.Mutable(index);
}
inline ::message::CrashMapData* CrashPlayerInfo::add_completemap() {
  // @@protoc_insertion_point(field_add:message.CrashPlayerInfo.CompleteMap)
  return completemap_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::message::CrashMapData >&
CrashPlayerInfo::completemap() const {
  // @@protoc_insertion_point(field_list:message.CrashPlayerInfo.CompleteMap)
  return completemap_;
}
inline ::google::protobuf::RepeatedPtrField< ::message::CrashMapData >*
CrashPlayerInfo::mutable_completemap() {
  // @@protoc_insertion_point(field_mutable_list:message.CrashPlayerInfo.CompleteMap)
  return &completemap_;
}

// required bool isadmin = 8;
inline bool CrashPlayerInfo::has_isadmin() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void CrashPlayerInfo::set_has_isadmin() {
  _has_bits_[0] |= 0x00000040u;
}
inline void CrashPlayerInfo::clear_has_isadmin() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void CrashPlayerInfo::clear_isadmin() {
  isadmin_ = false;
  clear_has_isadmin();
}
inline bool CrashPlayerInfo::isadmin() const {
  // @@protoc_insertion_point(field_get:message.CrashPlayerInfo.isadmin)
  return isadmin_;
}
inline void CrashPlayerInfo::set_isadmin(bool value) {
  set_has_isadmin();
  isadmin_ = value;
  // @@protoc_insertion_point(field_set:message.CrashPlayerInfo.isadmin)
}

// repeated .message.intPair resources = 9;
inline int CrashPlayerInfo::resources_size() const {
  return resources_.size();
}
inline void CrashPlayerInfo::clear_resources() {
  resources_.Clear();
}
inline const ::message::intPair& CrashPlayerInfo::resources(int index) const {
  // @@protoc_insertion_point(field_get:message.CrashPlayerInfo.resources)
  return resources_.Get(index);
}
inline ::message::intPair* CrashPlayerInfo::mutable_resources(int index) {
  // @@protoc_insertion_point(field_mutable:message.CrashPlayerInfo.resources)
  return resources_.Mutable(index);
}
inline ::message::intPair* CrashPlayerInfo::add_resources() {
  // @@protoc_insertion_point(field_add:message.CrashPlayerInfo.resources)
  return resources_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::message::intPair >&
CrashPlayerInfo::resources() const {
  // @@protoc_insertion_point(field_list:message.CrashPlayerInfo.resources)
  return resources_;
}
inline ::google::protobuf::RepeatedPtrField< ::message::intPair >*
CrashPlayerInfo::mutable_resources() {
  // @@protoc_insertion_point(field_mutable_list:message.CrashPlayerInfo.resources)
  return &resources_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace message

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_common_2eproto__INCLUDED
